apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: tenant-operator.v0.3.33
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IntegrationConfig is the Schema for the integrationconfigs API
      displayName: Integration Config
      kind: IntegrationConfig
      name: integrationconfigs.tenantoperator.stakater.com
      version: v1alpha1
    - description: Quota is the Schema for the quotas API
      displayName: Quota
      kind: Quota
      name: quotas.tenantoperator.stakater.com
      version: v1alpha1
    - kind: Quota
      name: quotas.tenantoperator.stakater.com
      version: v1beta1
    - description: TemplateGroupInstance is the Schema for the templategroupinstances
        API
      displayName: Template Group Instance
      kind: TemplateGroupInstance
      name: templategroupinstances.tenantoperator.stakater.com
      version: v1alpha1
    - description: TemplateInstance is the Schema for the templatesinstance API
      displayName: Template Instance
      kind: TemplateInstance
      name: templateinstances.tenantoperator.stakater.com
      version: v1alpha1
    - description: Template is the Schema for the templates API
      displayName: Template
      kind: Template
      name: templates.tenantoperator.stakater.com
      version: v1alpha1
    - description: Tenant is the Schema for the tenants API
      displayName: Tenant
      kind: Tenant
      name: tenants.tenantoperator.stakater.com
      version: v1alpha1
    - kind: Tenant
      name: tenants.tenantoperator.stakater.com
      version: v1beta1
  description: tenant operator
  displayName: tenant-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - argoproj.io
          resources:
          - appprojects
          - appprojects/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - limitranges
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - kubernetes-client.io
          resources:
          - externalsecrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - quota.openshift.io
          resources:
          - clusterresourcequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - integrationconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - integrationconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - integrationconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - quotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - quotas/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templategroupinstances
          - templateinstances
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templategroupinstances/finalizers
          verbs:
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templategroupinstances/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templateinstances
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templateinstances/finalizers
          verbs:
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templateinstances/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - templates/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - tenants
          - tenants/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tenantoperator.stakater.com
          resources:
          - tenants/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - user.openshift.io
          resources:
          - groups
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: tenant-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: tenant-operator-controller-manager
        spec:
          replicas: 2
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: ENABLE_ALL_CONTROLLERS
                  value: "true"
                - name: ENABLE_WEBHOOK
                  value: "true"
                - name: ENABLE_ADMISSION_WEBHOOKS
                  value: "true"
                - name: LEADER_ELECTION_ID
                  value: c54f40h1.stakater.com
                image: docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater-ab/tenant-operator:v0.3.33
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 15
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 15
                resources:
                  limits:
                    cpu: 2500m
                    memory: 3000Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              imagePullSecrets:
              - name: dockerconfigjson
              securityContext:
                runAsNonRoot: true
              serviceAccountName: tenant-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: tenant-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tenant
  - stakater
  - SRO
  links:
  - name: Tenant Operator
    url: https://tenant-operator.domain
  maintainers:
  - email: jose@stakater.com
    name: josebarato
  maturity: alpha
  provider:
    name: stakater
    url: https://stakater.com
  version: 0.3.33
  webhookdefinitions:
  - admissionReviewVersions:
    - v1alpha1
    - v1beta1
    containerPort: 443
    conversionCRDs:
    - quotas.tenantoperator.stakater.com
    - tenants.tenantoperator.stakater.com
    deploymentName: tenant-operator-controller-manager
    generateName: cquotastenants.kb.io
    sideEffects: None
    targetPort: 9443
    type: ConversionWebhook
    webhookPath: /convert
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: tenant-operator-controller-manager
    failurePolicy: Ignore
    generateName: vnamespace.kb.io
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - namespaces
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-v1-namespace
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: tenant-operator-controller-manager
    failurePolicy: Fail
    generateName: vquota.kb.io
    rules:
    - apiGroups:
      - tenantoperator.stakater.com
      apiVersions:
      - v1beta1
      operations:
      - DELETE
      resources:
      - quotas
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-tenantoperator-stakater-com-v1beta1-quota
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: tenant-operator-controller-manager
    failurePolicy: Ignore
    generateName: vrolebinding.kb.io
    rules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - rolebindings
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-v1-rolebinding
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: tenant-operator-controller-manager
    failurePolicy: Fail
    generateName: vtemplate.kb.io
    rules:
    - apiGroups:
      - tenantoperator.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - DELETE
      resources:
      - templates
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-tenantoperator-stakater-com-v1alpha1-template
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: tenant-operator-controller-manager
    failurePolicy: Fail
    generateName: vtemplategroupinstance.kb.io
    rules:
    - apiGroups:
      - tenantoperator.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - templategroupinstances
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-tenantoperator-stakater-com-v1alpha1-templategroupinstance
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: tenant-operator-controller-manager
    failurePolicy: Fail
    generateName: vtemplateinstance.kb.io
    rules:
    - apiGroups:
      - tenantoperator.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - templateinstances
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-tenantoperator-stakater-com-v1alpha1-templateinstance
