- op: replace
  path: /spec/install/spec/deployments/0/spec/template/spec/containers/0/image
  value: controller:latest

- op: replace
  path: /spec/install/spec/deployments/0/spec/template/spec/initContainers/0/image
  value: controller:latest
