---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
        [
          {
            "apiVersion": "eweb.enterpriseweb.com/v1",
            "kind": "CloudNFV",
            "metadata": {
              "name": "cloudnfv-sample"
            },
            "spec": null
          }
        ]
    capabilities: "Basic Install"
    operators.operatorframework.io/builder: operator-sdk-v1.22.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: cnfv-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      -
        description: "CloudNFV is the Schema for the cloudnfvs API"
        displayName: "Cloud NFV"
        kind: CloudNFV
        name: cloudnfvs.eweb.enterpriseweb.com
        version: v1
  description: "Manages a cluster of CloudNFV Runtime Modules"
  displayName: CloudNFV
  icon:
    -
      base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        -
          rules:
            -
              apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            -
              apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
                - list
                - watch
            -
              apiGroups:
                - eweb.enterpriseweb.com
              resources:
                - cloudnfvs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            -
              apiGroups:
                - eweb.enterpriseweb.com
              resources:
                - cloudnfvs/finalizers
              verbs:
                - update
            -
              apiGroups:
                - eweb.enterpriseweb.com
              resources:
                - cloudnfvs/status
              verbs:
                - get
                - patch
                - update
            -
              apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            -
              apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: cnfv-operator-controller-manager
      deployments:
        -
          label:
            control-plane: controller-manager
          name: cnfv-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  -
                    args:
                      - "--secure-listen-address=0.0.0.0:8443"
                      - "--upstream=http://127.0.0.1:8080/"
                      - "--logtostderr=true"
                      - "--v=0"
                    image: "registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:61a164ad711478ac603242338f7b3c55986319479878b092be128581a823598e"
                    name: kube-rbac-proxy
                    ports:
                      -
                        containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                  -
                    args:
                      - "--health-probe-bind-address=:8081"
                      - "--metrics-bind-address=127.0.0.1:8080"
                      - "--leader-elect"
                    command:
                      - /manager
                    image: "quay.io/wmalyk28/cnfv-op@sha256:e5913ad5dd20cb1b2299d2387237ef15e645c9a8c9d4f5fe0044b86a6b3dc1df"
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: cnfv-operator-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        -
          rules:
            -
              apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            -
              apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            -
              apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: cnfv-operator-controller-manager
    strategy: deployment
  installModes:
    -
      supported: false
      type: OwnNamespace
    -
      supported: false
      type: SingleNamespace
    -
      supported: false
      type: MultiNamespace
    -
      supported: true
      type: AllNamespaces
  keywords:
    - automation
    - NFV
    - controller
  links:
    -
      name: "Cnfv Operator"
      url: "https://cnfv-operator.domain"
  maintainers:
    -
      email: bill@enterpriseweb.com
      name: "Bill Malyk"
  maturity: alpha
  provider:
    name: EnterpriseWeb
  relatedImages:
    -
      image: "quay.io/wmalyk28/cnfv-op@sha256:e5913ad5dd20cb1b2299d2387237ef15e645c9a8c9d4f5fe0044b86a6b3dc1df"
      name: cnfv-operator
    -
      image: "quay.io/wmalyk28/cloudnfv-runtime@sha256:fcde8375576c9bff602d3a16ef1ba8ae88b780166649ba6ae355737b1d35a03f"
      name: cnfv-image
  spec: ~
  version: "0.0.1"
