---
# Source: listener-operator/templates/configmap.yaml
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: listener-operator-configmap
  labels:
    helm.sh/chart: listener-operator-24.3.0
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    stackable.tech/vendor: Stackable
    app.kubernetes.io/version: "24.3.0"
    app.kubernetes.io/managed-by: Helm
