---
# Source: listener-operator/templates/roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: listener-operator-clusterrole
  labels:
    helm.sh/chart: listener-operator-24.3.0
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    stackable.tech/vendor: Stackable
    app.kubernetes.io/version: "24.3.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumeclaims
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - listeners.stackable.tech
    resources:
      - listenerclasses
      - listeners
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - listeners.stackable.tech
    resources:
      - listeners
      - listeners/status
      - podlisteners
    verbs:
      - patch
      - create
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - hostmount-anyuid
    verbs:
      - use
