---
# Source: listener-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: listener-operator-serviceaccount
  labels:
    helm.sh/chart: listener-operator-24.3.0
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    stackable.tech/vendor: Stackable
    app.kubernetes.io/version: "24.3.0"
    app.kubernetes.io/managed-by: Helm
