---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: commons-operator.v23.4.1
spec:
  annotations:
    support: stackable.tech
    olm.properties: '[]'
    categories: Storage
    capabilities: Full Lifecycle
    description: Stackable Commons Operator
    repository: https://github.com/stackabletech/commons-operator
    containerImage: docker.stackable.tech/stackable/commons-operator@sha256:7abef3834d10640b2d4d5d9354fc3cb0993f3dcdb07c9407b0bf6baa5e96e889

  displayName: Stackable Commons Operator
  description: |-
    This is a Kubernetes operator to provide common functionality to other Stackable operators. The Stackable Commons Operator
    is part of the Stackable Data Platform, a curated selection of the best open source data apps like Kafka, Druid, Trino or Spark, all
    working together seamlessly. Based on Kubernetes, it runs everywhere – on prem or in the cloud.

    You can install the operator using [stackablectl or helm](https://docs.stackable.tech/home/stable/commons-operator/installation.html).
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAJYAAAAaCAYAAABVc6VBAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAuNSURBVHgB7VrPbxvHFX6zS9l0Asd0g9Qy7MJU20MOBUxfCvRkKnKdpIdYuuVm6Vb3EMvHAi24BIr0aAo9OD2ZuhVoC1NFEaNxbFF/gamihwBB43XQQpJTRGvHlkiR3On3ZmaXS2pJkZQc2Ag/QFhqd368mX3z3vveW6IRRhhhhJcFIu5mKrecGqN62iY7IwWdFSQyaJgpOn8mSVRBk4pFvtsksYrf7rv0kUtDgOdJkj8NKc60CSUsr+k3H0rMUacx18tPevSSYDx3J0vCWubf686UoG8JBzHvuHP3AS5p/DkYI0/7QOKN3CeZQIF4UFYiIj9NZKsGWkLJCqX+gCz/+WSFWvkPuuIZhfMEyQor3C/oRqnbpKxQR4R/U7JSxUBKjC54dEhGPo3n72XXc2+t0AgvDRK2sO/zj5aKSxoU6JEirXD4LaYtfburNUwKeV/qk8Fw0auM5m4wFpSTx4OS87giTbZ0o2OM55bTJPwHehYxUroXEIkez1x+4TAcFUGWK20J99c4ji7HYNEykqws7FiKLZxRrL4A1zdPLaXat8kd4cVEQtRrZNe2yKpukf69Xfii+MG1uMYXiR6an2whFoL7P33vd7nXn9adU16dXn/WoB89qnm0GT+hEOKSdqxU3J9SsZWDigvx0sRf3yUkjv17daJJlEOMNavuSDnwi/r6FYu+fjVJn48nPfJloVGtLVCXCAtKlVFXISs0JNbzky4ukzTCC4vEZ3/6tYvr3Jvv/z7PCgabElglOpn7dFoqC8OsUIIV/gV3BRRCukGQjquX32rQ/15JOI3t2oJbyj83C6JiK/Kze7WrklUKmGRATgzzTOsWQl2h5BUh/aX1/M/LvcZTZMOiyyAVGR0DihTvAR65vpSrO2SX+2Gut+mXaTKxaJWSpRkqeO3ru532aSxjW/YZX/oqxgzmg6we2HIJXGbFHKyeYJYorMRZlpnXq/ozwZLWYj/9uyG6F9F9lFKuPMpfCM1J4vtQHl6IpzZNZMDGQkvCSoXLrGgL6JXFybSCdEHO39bIKFyW6IpKRVykPy50kc0lfsFSoC11a9MFDQTt1s29Wh1J+Mt4Y54J8u/vbiGN5MQUff6Ec7ew4UzFuv/x3N1ZIeR1bFzK9KEowWH2CjKSJR0e9AQUhNMBad4rKFVxd4PDNy3sIbNiEfbR86mr5NSMcLGuyV7KcdK5d589A49D0f5E6O87WFN+PT/l0IBQyirkrWAvovuIEGd+3Lnn4r0q2RLYmFuBAKxArU6DQrs4MqkI6qI0EKIEceZxncYCncEWmHBhsRxzkufNzSJpZQ2xXbce8zUJ5aqSLCrGKSzVBi/Ow2o9i8eQchbjTGO8eWzaLstlFPOm1C+G+xVhNSqttTQxBqyXX3tIe+A2/crBHqVZVqRZZmIbycaiFHbFEhJtbGPNNCMWIEx4aY7kMQTx4eoRCvA8iniV9DjsYWA4pNDESVAO6y3vZamjMHuxbBJPZRJ20fbrq00LZM5vTOD/HGnZ+PBM9GKFJKRcwpuogAFWqv7j1W06TK9SjROmqaayTjKjzTRlqE9IubNA4tB0uEDn3mUWFC5lySK70uskmmd5s0itWEIUu6UbXO2e5qg7ljD/srK0woIcVG57KvxcMBTkntzIv+vSEPiYrkB5pRoLCuq80yWhvJ6/WOwxzMrJ/KfsRgosL7ukbu53Wz6Z8PIznc9W4GqXhDh0X7H4uPX2gpCBpwDpujAXM3ZZjy3T4/nlywl764lihFajppnhTj1svRbxmQxzzIKXuBTc//H7H+ZOe3Xne8+adHpzh374VdWjDYrFOl4OhJiEcvFGz5pTPAvLid9IhrI55RMh/cVBTtSw4FhRqrhHydHxjKZNYrg0rFJxXIVxrpt/C2/TjUUaEtK3l6DsBf7NlRHSSeldiFEqBd77k87dImlrn6U+0Rbbyp18t7GRuWd9mYUHnLaOfvnZRPLRl8WxzQ2yt7+Bgm3TMPjP8UP0zx8c8T7+yWtO4WfHJnq1ZSGQapiDkBPw2fNB6kBDKxqXJ6BkD/Sinh+gNLEv4VRuOczPIX4oUZ/gwyASSO4mNFFAkO6NkZXFXxoW/8Bydja7oCEgJa2an2m2ev30gcvXTB6HcL3HAROG6XP5bxcr5BOqa3iNTMAqVFAPQSK1Qo43FoOyzRtP696jo2Ozza3a0iCs0Ai5YP64dHO+LRYwPhvynDuIeiGzLr4y80JBKiUs6xjirGxctaFJjRSRoScdmf+9sPabqTDmMsxvYNn1O6hChkQacqSVHMI/O3hdpBO+G6zryJh/zOtDNpC4s2r+PdpKXzw2LCGdCGjppqK3gs32NLLjjgpzo0E9tdUKVRCMi1Is5+9rXHpBYMkKcUWlIt6mjwY+nSZWUslXmFV2lQ4r12HL53hgQAapYeKxHNY2LXWpyGwrUYs19UZABvqbr1UM7gSsxbWN/FShd/+7DjTovHY9h9r700FAESAaEGk9v8jomLRXOy1lgjehRW/l0MJrt9FKReC6L7PPWXnQZlaGjJCib3IQBbszX8hlIxuzoyIzRJhsL2BLsFiKFdJzAZgZTrmeH+kVxcaWS90IygmkCfQeauaFfawoKwFGaw4y8s+yb7c8tNSiI0kumyuQYVeqJQaubiG9WFaoTR5TXtQJI7VCxAiPmRVyrbBB1p4Ue79gn06Kce4OrPtBE/kn0lbKBVM6FxfUwjJm9xqnX5fRCbAnlRJIw61VkU8TignL2FSBSka3qhLzG7kLuyy0tr77tVvIBYY2Ox6dLs+w1SINgISFOqHNrLD2DLXCHbLqO11rhRFW2Ebvf/veaUKtkPqpFQ4GkdZWdNh6oEpc8osqeM7MgGO0XEaj3kTxnYY+SJz2gOJcQ6xyi2ViOr6em2xnh8r96cMUp1QHBZMeUojGglF0flRwCtWLprAvsSXrVzbrtQf/mkiufVE8tLnhJp5uIuXwNPYFcDB5i+ZjWQTXCj8/kaTym0e9v55LOR+eT03QwSBtrm705qAlCTGEtUlG+liWdZ72CU7dCBOTIvQodDKykIEOIesgMNWUwBvEQnDSNwJfkwcH9wv9MskoK0yDFWabrxw7E5R5dL1Kfz2KbHHqCNWiH/WFX5H+4dEOF6Dn61vbiwdVK1RBrHGBcXS/FbvwR4nx5ZSwjRRpGhBsZRColpXVk9YsDUkeojgsrbmaUPmgVFL4nNua65BVBcj0nKBTN5oFCxKVfvsdRi20Rr7aS8h9lfqInxMn88tXOaWwaVIKzJzYA3cL6CMf9YVfkX5wbyPYGATtV7xerJBrb6ogLNm1MPVlNNzguUoFCOtq4MaIM70xmXVpapNSWijHLKvCbJBO4NwRpydkWL8Us2gTFl+DdIoU1iVs8KzU7jbDG99mDVFiQa4hywV4zqnhoF2zqF7h8TkV0CQ7ZcO1VClR6Scdol3inTwCYVYqyHQnTAJjv5e4bsnlqs5SF69LWMlLTDRC0fTvlfg91vvA6ZwgbWH6z4fxapdEZze5EYsWSLF04lqjaFKz9FX+YqVzTr0nY55Ah76jQf11Q394h26IuPthCaUvyHJVfjMTG3TnPoGC2rEF6aZsnuNFm9ggLEJDibwg5dC6F1g+8z9e7lpuMrROyFRfl3uxxshXrP18e97aA+FWpQhzdJ17s5e8/HzNeet457w9ReX+IAfruQuLu+Xq/s17QECoFZ50BY9v0bcN2cybbHtR03Hl611+ZOILVz3jlwVW1b08AaYim3OiPVZQOTRhJ9Rh+S+fKGT3W7Sfv3jV3+WjQYHnWHOmjvM4YRvpt73INf7qQc9TiptLydpWhE64Zm1F6roHtTn93C/DmoSuLynFDGQotOaRwTwl3rOqfHIcNctzxMVwtYao0ql5y6aK4XbEauYZOVxHjFMqM1uJ5fJlY7XzGVstKNtEdK/ax9dycn/hy1UaYYQRRnhp8H8CyBxMQxNX6AAAAABJRU5ErkJggg==
      metadata: image/png
  keywords:
    - commons
  maintainers:
    - email: info@stackable.tech
      name: Stackable GmbH
  maturity: stable
  provider:
    name: Stackable GmbH
    url: https://stackable.tech
  version: 23.4.1
  minKubeVersion: 1.23.0

  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces

  customresourcedefinitions:
    owned:
      # a list of CRDs that this operator owns
      # name is the metadata.name of the CRD (which is of the form <plural>.<group>)
      - name: s3buckets.s3.stackable.tech
        # version is the spec.versions[].name value defined in the CRD
        version: v1alpha1
        # kind is the CamelCased singular value defined in spec.names.kind of the CRD.
        kind: S3Bucket
        # human-friendly display name of the CRD for rendering in graphical consoles (optional)
        displayName: S3Bucket
        # a short description of the CRDs purpose for rendering in graphical consoles (optional)
        description: Represents an S3 bucket
      - name: s3connections.s3.stackable.tech
        # version is the spec.versions[].name value defined in the CRD
        version: v1alpha1
        # kind is the CamelCased singular value defined in spec.names.kind of the CRD.
        kind: S3Connection
        # human-friendly display name of the CRD for rendering in graphical consoles (optional)
        displayName: S3Connection
        # a short description of the CRDs purpose for rendering in graphical consoles (optional)
        description: Represents an S3Connection
      - name: authenticationclasses.authentication.stackable.tech
        # version is the spec.versions[].name value defined in the CRD
        version: v1alpha1
        # kind is the CamelCased singular value defined in spec.names.kind of the CRD.
        kind: AuthenticationClass
        # human-friendly display name of the CRD for rendering in graphical consoles (optional)
        displayName: AuthenticationClass
        # a short description of the CRDs purpose for rendering in graphical consoles (optional)
        description: Represents an AuthenticationClass

  relatedImages:
    - name: commons-operator
      image: docker.stackable.tech/stackable/commons-operator@sha256:7abef3834d10640b2d4d5d9354fc3cb0993f3dcdb07c9407b0bf6baa5e96e889
  install:
    # strategy indicates what type of deployment artifacts are used
    strategy: deployment
    # spec for the deployment strategy is a list of deployment specs and required permissions - similar to a pod template used in a deployment
    spec:
      permissions:
        - serviceAccountName: commons-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - '*'
      # permissions required at the cluster scope
      clusterPermissions:
        - serviceAccountName: commons-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - configmaps
                - secrets
                - nodes
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - get
                - list
                - watch
                - patch
            - apiGroups:
                - events.k8s.io
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - s3.stackable.tech
              resources:
                - s3buckets
                - s3connections
              verbs:
                - get
                - list
                - patch
                - watch
            - apiGroups:
                - authentication.stackable.tech
              resources:
                - authenticationclasses
              verbs:
                - get
                - list
                - patch
                - watch
            - apiGroups:
                - ""
              resources:
                - pods/eviction
              verbs:
                - create

      deployments:
        - name: commons-operator
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                app.kubernetes.io/name: commons-operator
                app.kubernetes.io/instance: commons-operator
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: commons-operator
                  app.kubernetes.io/instance: commons-operator
              spec:
                serviceAccountName: commons-operator
                securityContext: {}
                containers:
                  - name: commons-operator
                    securityContext: {}
                    image: "docker.stackable.tech/stackable/commons-operator@sha256:7abef3834d10640b2d4d5d9354fc3cb0993f3dcdb07c9407b0bf6baa5e96e889"
                    imagePullPolicy: IfNotPresent
                    resources: {}
