apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: citrix-multi-cluster-ingress-controller-operator
    app.kubernetes.io/instance: ctrlmgrmtrssvc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: citrix-multi-cluster-ingress-controller-operator
    control-plane: controller-manager
  name: citrix-multi-cluster-ingress-controller-operator-ctrlmgrmtrssvc
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
