---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "logs.grafana.com/v1alpha1",
          "kind": "GrafanaCloudLogForwarder",
          "metadata": {
            "name": "grafanacloudlogforwarder-sample",
            "namespace": "openshift-logging"
          },
          "spec": {
            "url": "******",
            "username": "******",
            "apipassword": "******"
          }
        }
      ]
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: openshift-logging
    operators.operatorframework.io/builder: operator-sdk-v1.12.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: grafana-cloud-log-forwarder-operator.v1.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: GrafanaCloudLogForwarder is the Schema for the grafanacloudlogforwarders API
        displayName: Grafana Cloud Log Forwarder
        kind: GrafanaCloudLogForwarder
        name: grafanacloudlogforwarders.logs.grafana.com
        specDescriptors:
          - description: URL to loki datasource
            displayName: URL
            path: url
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: The username from the loki endpoint
            displayName: Username
            path: username
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:text
          - description: Enter API key to authenticate clusterLogForwarder to loki datasource
            displayName: APIPassword
            path: apipassword
            x-descriptors:
              - urn:alm:descriptor:com.tectonic.ui:password
        version: v1alpha1
  description: |
    Grafana Cloud is a completeobservability stack for metrics, logs, and traces that's tightly integrated with Grafana.
    Leverage the best open source observability software without the overhead of installing, maintaining, and scaling your observability stack.
  displayName: Grafana Cloud Log Forwarder
  icon:
    - base64data: PHN2ZyB3aWR0aD0iNDgiIGhlaWdodD0iNTYiIHZpZXdCb3g9IjAgMCA0OCA1NiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyLjA0NzggNTQuOTI0OEwxMS4zODM4IDUwLjQ2NjNMNi45MjUyOSA1MS4xMzA0TDcuNjg0MTggNTUuNTg4OUwxMi4wNDc4IDU0LjkyNDhaIiBmaWxsPSJ1cmwoI3BhaW50MF9saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNNDYuOTU3IDQyLjQwMzJMNDYuMTk4MSAzOC4wMzk2TDI2Ljc1MTUgNDEuMDc1MUwyNy4zMjA2IDQ1LjQzODhMNDYuOTU3IDQyLjQwMzJaIiBmaWxsPSJ1cmwoI3BhaW50MV9saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNMjAuMzk1IDQ2LjU3NzJMMjQuODUzNSA0NS44MTgzTDI0LjE4OTUgNDEuNDU0NkwxOS43MzEgNDIuMTE4NkwyMC4zOTUgNDYuNTc3MloiIGZpbGw9InVybCgjcGFpbnQyX2xpbmVhcl8xNzkzMV84OTMpIi8+CjxwYXRoIGQ9Ik0xOS4wNjc0IDUzLjc4NjVMMTguMzA4NSA0OS40MjI5TDEzLjk0NDggNTAuMDg2OUwxNC41MTQgNTQuNTQ1NEwxOS4wNjc0IDUzLjc4NjVaIiBmaWxsPSJ1cmwoI3BhaW50M19saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNNS44ODEzNSA0NC4yMDU1TDYuNTQ1MzkgNDguNjY0MUwxMS4wMDM5IDQ4TDEwLjMzOTkgNDMuNTQxNUw1Ljg4MTM1IDQ0LjIwNTVaIiBmaWxsPSJ1cmwoI3BhaW50NF9saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNMjcuNjk5NyA0Ny45MDUxTDI4LjQ1ODYgNTIuNDU4NUw0OC4wMDAxIDQ5LjQyMjlMNDcuMzM2MSA0NC45NjQ0TDI3LjY5OTcgNDcuOTA1MVoiIGZpbGw9InVybCgjcGFpbnQ1X2xpbmVhcl8xNzkzMV84OTMpIi8+CjxwYXRoIGQ9Ik0yMS41MzMzIDUzLjQwN0wyNS44OTY5IDUyLjgzNzhMMjUuMjMyOSA0OC4yODQ0TDIwLjc3NDQgNDkuMDQzM0wyMS41MzMzIDUzLjQwN1oiIGZpbGw9InVybCgjcGFpbnQ2X2xpbmVhcl8xNzkzMV84OTMpIi8+CjxwYXRoIGQ9Ik0xMi44MDYyIDQzLjE2MjFMMTMuNTY1IDQ3LjYyMDVMMTcuOTI4NyA0Ni45NTY2TDE3LjI2NDYgNDIuNDk4TDEyLjgwNjIgNDMuMTYyMVoiIGZpbGw9InVybCgjcGFpbnQ3X2xpbmVhcl8xNzkzMV84OTMpIi8+CjxwYXRoIGQ9Ik03LjM5OTIxIDQxLjQ1NDZMMS45OTIwNyA1Ljk3NjMyTDAgNi4yNjA4OUw1LjUwMTk3IDQxLjczOTJMNy4zOTkyMSA0MS40NTQ2WiIgZmlsbD0idXJsKCNwYWludDhfbGluZWFyXzE3OTMxXzg5MykiLz4KPHBhdGggZD0iTTkuOTYwMzIgNDEuMDc1MUw0LjA3ODg4IDIuOTQwNjdMMi4xODE2NCAzLjMyMDE0TDguMDYzMDggNDEuMzU5N0w5Ljk2MDMyIDQxLjA3NTFaIiBmaWxsPSJ1cmwoI3BhaW50OV9saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNMTQuMzI0NSA0MC40MTExTDguMTU4NDcgMEw2LjI2MTIzIDAuMzc5NDEyTDEyLjQyNzIgNDAuNjAwOEwxNC4zMjQ1IDQwLjQxMTFaIiBmaWxsPSJ1cmwoI3BhaW50MTBfbGluZWFyXzE3OTMxXzg5MykiLz4KPHBhdGggZD0iTTE2Ljg4NTIgNDAuMDMxNUwxMS4xOTM1IDMuMjI1MUw5LjM5MTExIDMuNTA5NjdMMTUuMDgyOCA0MC4yMjEyTDE2Ljg4NTIgNDAuMDMxNVoiIGZpbGw9InVybCgjcGFpbnQxMV9saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNMjEuMjQ5MSAzOS4yNzI4TDE2LjIyMTUgNi42NDAzOEwxNC4zMjQyIDYuOTI0OTVMMTkuMzUxOSAzOS42NTIzTDIxLjI0OTEgMzkuMjcyOFoiIGZpbGw9InVybCgjcGFpbnQxMl9saW5lYXJfMTc5MzFfODkzKSIvPgo8cGF0aCBkPSJNMjMuODEwNCAzOC44OTM1TDE4LjU5MyA1LjAyNzgzTDE2LjY5NTggNS4zMTI0MUwyMi4wMDgxIDM5LjE3ODFMMjMuODEwNCAzOC44OTM1WiIgZmlsbD0idXJsKCNwYWludDEzX2xpbmVhcl8xNzkzMV84OTMpIi8+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9InBhaW50MF9saW5lYXJfMTc5MzFfODkzIiB4MT0iMTEuNjQ2OSIgeTE9IjY2Ljg3NzIiIHgyPSIxLjIzMTk4IiB5Mj0iLTAuODAyNTAxIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CjxzdG9wIHN0b3AtY29sb3I9IiNGQUVEMUUiLz4KPHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRjE1QjJCIi8+CjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0icGFpbnQxX2xpbmVhcl8xNzkzMV84OTMiIHgxPSIzOS45OTE2IiB5MT0iNjIuNTE1NCIgeDI9IjI5LjU3NjgiIHkyPSItNS4xNjM5IiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CjxzdG9wIHN0b3AtY29sb3I9IiNGQUVEMUUiLz4KPHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRjE1QjJCIi8+CjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0icGFpbnQyX2xpbmVhcl8xNzkzMV84OTMiIHgxPSIyNS41MDYzIiB5MT0iNjQuNzQ0NSIgeDI9IjE1LjA5MTMiIHkyPSItMi45MzUxNiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjRkFFRDFFIi8+CjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI0YxNUIyQiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9InBhaW50M19saW5lYXJfMTc5MzFfODkzIiB4MT0iMTguNTc4OCIgeTE9IjY1LjgxMDUiIHgyPSI4LjE2MzgiIHkyPSItMS44NjkyMiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjRkFFRDFFIi8+CjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI0YxNUIyQiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9InBhaW50NF9saW5lYXJfMTc5MzFfODkzIiB4MT0iMTEuNjM5NCIgeTE9IjY2Ljg3ODQiIHgyPSIxLjIyNDQ4IiB5Mj0iLTAuODAxMjgiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iI0ZBRUQxRSIvPgo8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNGMTVCMkIiLz4KPC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJwYWludDVfbGluZWFyXzE3OTMxXzg5MyIgeDE9IjM5Ljk5ODIiIHkxPSI2Mi41MTQzIiB4Mj0iMjkuNTgzMyIgeTI9Ii01LjE2NTI4IiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CjxzdG9wIHN0b3AtY29sb3I9IiNGQUVEMUUiLz4KPHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRjE1QjJCIi8+CjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0icGFpbnQ2X2xpbmVhcl8xNzkzMV84OTMiIHgxPSIyNS41MDYiIHkxPSI2NC43NDQzIiB4Mj0iMTUuMDkxIiB5Mj0iLTIuOTM1MzciIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iI0ZBRUQxRSIvPgo8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNGMTVCMkIiLz4KPC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJwYWludDdfbGluZWFyXzE3OTMxXzg5MyIgeDE9IjE4LjU3ODgiIHkxPSI2NS44MTAzIiB4Mj0iOC4xNjQwNyIgeTI9Ii0xLjg2ODY3IiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CjxzdG9wIHN0b3AtY29sb3I9IiNGQUVEMUUiLz4KPHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRjE1QjJCIi8+CjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0icGFpbnQ4X2xpbmVhcl8xNzkzMV84OTMiIHgxPSIxMC4xNjIzIiB5MT0iNjUuNzU5NyIgeDI9IjAuMjg0Njk2IiB5Mj0iMS41NzE2NiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjRkFFRDFFIi8+CjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI0YxNUIyQiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9InBhaW50OV9saW5lYXJfMTc5MzFfODkzIiB4MT0iMTMuMDEyOSIgeTE9IjY3LjE0MzEiIHgyPSIyLjQwNzg1IiB5Mj0iLTEuNzcyNDMiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iI0ZBRUQxRSIvPgo8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNGMTVCMkIiLz4KPC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJwYWludDEwX2xpbmVhcl8xNzkzMV84OTMiIHgxPSIxNy42MzM4IiB5MT0iNjguMDMzMSIgeDI9IjYuMzg5NDMiIHkyPSItNS4wMzY3IiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CjxzdG9wIHN0b3AtY29sb3I9IiNGQUVEMUUiLz4KPHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjRjE1QjJCIi8+CjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0icGFpbnQxMV9saW5lYXJfMTc5MzFfODkzIiB4MT0iMTkuODMwNSIgeTE9IjY1LjIwOCIgeDI9IjkuNTc5MjUiIHkyPSItMS40MDgzMiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjRkFFRDFFIi8+CjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI0YxNUIyQiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9InBhaW50MTJfbGluZWFyXzE3OTMxXzg5MyIgeDE9IjIzLjczNTMiIHkxPSI2MS43MzkzIiB4Mj0iMTQuNjI4OSIgeTI9IjIuNTYyNDYiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iI0ZBRUQxRSIvPgo8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNGMTVCMkIiLz4KPC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJwYWludDEzX2xpbmVhcl8xNzkzMV84OTMiIHgxPSIyNi40NDY1IiB5MT0iNjIuMTk2NyIgeDI9IjE2Ljk5MTEiIHkyPSIwLjc1MTg1MSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjRkFFRDFFIi8+CjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI0YxNUIyQiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8L2RlZnM+Cjwvc3ZnPgo=
      mediatype: image/png
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - logging.openshift.io
              resources:
                - clusterlogforwarders
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - logging.openshift.io
              resources:
                - clusterloggings
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - logs.grafana.com
              resources:
                - grafanacloudlogforwarders
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - logs.grafana.com
              resources:
                - grafanacloudlogforwarders/finalizers
              verbs:
                - update
            - apiGroups:
                - logs.grafana.com
              resources:
                - grafanacloudlogforwarders/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: grafana-cloud-log-forwarder-operator-controller-manager
      deployments:
        - name: grafana-cloud-log-forwarder-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=10
                    image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:06b389c049dd4648257abf151f16e03d3c518a625a96fe68a63365ea86678514
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources: {}
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                    command:
                      - /manager
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                    image: docker.io/grafana/openshift-cloud-log-forwarder@sha256:9cb04cb779615c2b42ee37528da7f5abf71dc40c238de0c601035c9cf8fa1bc4
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 200m
                        memory: 100Mi
                      requests:
                        cpu: 100m
                        memory: 20Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: grafana-cloud-log-forwarder-operator-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: grafana-cloud-log-forwarder-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - clusterlogging
    - clusterlogforwarder
    - grafanacloudlogforwarder
  links:
    - name: Grafanacloud Operator
      url: https://grafana-cloud-log-forwarder-operator.domain
  maintainers:
    - email: support@grafana.com
      name: Trevor Whitney
  maturity: alpha
  provider:
    name: Grafana
  relatedImages:
    - name: ose-kube-rbac-proxy
      image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:06b389c049dd4648257abf151f16e03d3c518a625a96fe68a63365ea86678514
    - name: openshift-cloud-log-forwarder
      image: docker.io/grafana/openshift-cloud-log-forwarder@sha256:9cb04cb779615c2b42ee37528da7f5abf71dc40c238de0c601035c9cf8fa1bc4
  version: 1.0.1
