---
# Source: hdfs-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hdfs-operator-serviceaccount
  labels:
    helm.sh/chart: hdfs-operator-0.0.0-dev
    app.kubernetes.io/name: hdfs-operator
    app.kubernetes.io/instance: hdfs-operator
    app.kubernetes.io/version: "0.0.0-dev"
    app.kubernetes.io/managed-by: Helm
