apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "workloadmanager.nec.com/v1",
          "kind": "WorkloadManager",
          "metadata": {
            "name": "workload-manager",
            "namespace": "nec-workload-manager"
          },
          "spec": {
            "api_timeout": 3,
            "cluster_collection_size": 10737418240,
            "cluster_platform": "OpenShift",
            "common_config_log_level": "INFO",
            "db_startup_recheck_time": 5,
            "db_startup_wait_time": 60,
            "default_monitor_count": 10,
            "default_monitor_interval": 60,
            "default_repeat_interval": 1800,
            "detail_collection_size": 10737418240,
            "detect_count": 1,
            "detect_interval": 60,
            "event_collection_size": 10737418240,
            "expire_after_seconds": 31536000,
            "get_info_interval": 60,
            "get_info_ssc": "off",
            "grafana_cooperation": "off",
            "grafana_datasource": "prometheus",
            "grafana_node_additional_varlist": "None",
            "grafana_node_dashboard_endpoint": "https://changeit.nec.co.jp:443/d/wmnode/wm-node-dashboard",
            "grafana_node_varname_datasource": "datasource",
            "grafana_node_varname_node": "node",
            "grafana_pod_additional_varlist": "None",
            "grafana_pod_dashboard_endpoint": "https://changeit.nec.co.jp:443/d/wmpod/wm-pod-dashboard",
            "grafana_pod_varname_datasource": "datasource",
            "grafana_pod_varname_pod": "pod",
            "grafana_time_range_minutes": 60,
            "hidden_namespace": "None",
            "image": "registry.connect.redhat.com/nec/nec-workload-manager:1.3.0",
            "jaeger_endpoint": "https://changeit.nec.co.jp:443/search",
            "jaeger_service_mapping": "{None}",
            "jaeger_time_range_sec": 60,
            "max_policy_fired_histories": 512,
            "mode": "trial",
            "node_cpu_usage_threshold": 80,
            "node_disk_usage_threshold": 100,
            "node_memory_usage_threshold": 80,
            "node_network_usage_threshold": 55,
            "openshift": {
              "use_ebs": "n",
              "web_console_host": "REPLACE_WEB_CONSOLE_HOST"
            },
            "policy_fired_histories_collection_max_size": 1073741824,
            "policy_fired_histories_expire_after_seconds": 31536000,
            "skip_action_interval": 600,
            "ssc_auth_by_secret": "false",
            "ssc_event_collection_size": 1073741824,
            "use_auth": "false",
            "use_pv": "false",
            "user_authority_config_json": "[\n  {\n    \"username\": \"cluster-admin-user\",\n    \"is_cluster_admin\": true,\n    \"namespaces\": []\n  },\n  {\n    \"username\": \"tenant-user\",\n    \"is_cluster_admin\": false,\n    \"namespaces\": [\n      \"tenant-namespace\"\n    ]\n  }\n]\n"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.13.0+git
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: workload-manager-operator.v1.3.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: WorkloadManager
      name: workloadmanagers.workloadmanager.nec.com
      version: v1
  description: This operator deploys the NEC Workload Manager for Container Platform
    on OpenShift Container Platform.
  displayName: NEC Workload Manager for Container Platform Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: workload-manager-operator-workload-manager-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: workload-manager-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: workload-manager-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: workload-manager-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: registry.connect.redhat.com/nec/nec-workload-manager-operator:1.3.0
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 3
                name: workload-manager-operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: workload-manager-operator-workload-manager-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - workload-manager-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - workloadmanager.nec.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: workload-manager-operator-workload-manager-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - workload-manager-operator
  - nec
  - NEC
  links:
  - name: Workload Manager Operator
    url: https://workload-manager-operator.domain
  maturity: alpha
  provider:
    name: NEC Corporarion
    url: https://jpn.nec.com/
  version: 1.3.0
