---
# Source: opa-operator/templates/configmap.yaml
apiVersion: v1
data:
  properties.yaml: |
    version: 0.1.0
    spec:
      units: []

    properties: []
kind: ConfigMap
metadata:
  name: opa-operator-configmap
  labels:
    helm.sh/chart: opa-operator-0.0.0-dev
    app.kubernetes.io/name: opa-operator
    app.kubernetes.io/instance: opa-operator
    app.kubernetes.io/version: "0.0.0-dev"
    app.kubernetes.io/managed-by: Helm
